Improve ssh keys script usability

diff --git a/scripts/utils/ssh-keys b/scripts/utils/ssh-keys
--- a/scripts/utils/ssh-keys
+++ b/scripts/utils/ssh-keys
@@ -10,12 +10,11 @@ source "$DOTFILES_PATH/scripts/core/_main.sh"
 ##?
 ##? Usage:
 ##?     ssh-keys create [--keyname=<keyname>]
-##?     ssh-keys public <private_keyname>
+##?     ssh-keys public --keyname=<keyname>
 ##?
 ##? Arguments:
-##?   crete             Description of create
-##?   public            Description of public
-##?   private_keyname   Description of private_keyname
+##?   crete   Crates a ssh keypair
+##?   public  Extracts the PULIC key from the give private key
 ##?
 ##? Options:
 ##?   -k, --keyname=<keyname>  SSH key name [default: id_rsa]
@@ -25,6 +24,9 @@ docs::eval "$@"
 if ${create}; then
   ssh-keygen -t rsa -b 4096 -m pem -f ${keyname}
 elif ${public}; then
-  [[ -f ${private_keyname} ]] || echo "Error: ${private_keyname} does not exists"
-  ssh-keygen -f ${private_keyname} -y 
+  if [[ ! -f ${keyname} ]]; then
+    echo "Error: ${keyname} does not exists"
+    exit 1
+  fi
+  ssh-keygen -f ${keyname} -y 
 fi
